import { AIModel, Category } from '@/types';

const NOW = new Date().toISOString();

export const CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Coding', icon: 'Code2', created_at: NOW },
  { id: 'cat-2', name: 'Writing', icon: 'PenTool', created_at: NOW },
  { id: 'cat-3', name: 'Reasoning', icon: 'Brain', created_at: NOW },
  { id: 'cat-4', name: 'Image Generation', icon: 'Image', created_at: NOW },
  { id: 'cat-5', name: 'Conversation', icon: 'MessageSquare', created_at: NOW },
  { id: 'cat-6', name: 'Summarization', icon: 'FileText', created_at: NOW },
  { id: 'cat-7', name: 'Translation', icon: 'Globe', created_at: NOW },
  { id: 'cat-8', name: 'Data Analysis', icon: 'BarChart3', created_at: NOW },
  { id: 'cat-9', name: 'Math', icon: 'Calculator', created_at: NOW },
];

export const INITIAL_MODELS: AIModel[] = [
  {
    id: 'model-1',
    name: 'GPT-4o',
    provider: 'OpenAI',
    description: "OpenAI's flagship multimodal model. Excels at reasoning, coding, and creative tasks with vision capabilities.",
    type: 'text',
    api_available: true,
    website_url: 'https://openai.com',
    rating: 4.7,
    context_window: 128000,
    overall_score: 4.5,
    last_updated: '2026-03-15',
    created_at: '2024-05-13',
    categories: [CATEGORIES[0], CATEGORIES[1], CATEGORIES[2], CATEGORIES[4]],
    features: [
      { id: 'f1', model_id: 'model-1', type: 'strength', content: 'Excellent multimodal understanding', created_at: NOW },
      { id: 'f2', model_id: 'model-1', type: 'strength', content: 'Fast response times', created_at: NOW },
      { id: 'f4', model_id: 'model-1', type: 'weakness', content: 'Higher cost', created_at: NOW },
    ],
    pricing: { id: 'p1', model_id: 'model-1', input_price_per_1m_tokens: 2.50, output_price_per_1m_tokens: 10.00, pricing_type: 'paid', notes: 'Volume discounts via Batch API', created_at: NOW },
    metrics: { id: 'm1', model_id: 'model-1', reasoning: 4.5, coding: 4.5, speed: 4.0, latency: 4.0, creative_writing: 4.5, context_utilization: 4.5, created_at: NOW },
  },
  {
    id: 'model-2',
    name: 'GPT-4.1',
    provider: 'OpenAI',
    description: "Optimized for coding, instruction following, and massive 1M token context tasks.",
    type: 'text',
    api_available: true,
    website_url: 'https://openai.com',
    rating: 4.8,
    context_window: 1000000,
    overall_score: 4.7,
    last_updated: '2026-03-15',
    created_at: '2025-04-14',
    categories: [CATEGORIES[0], CATEGORIES[2], CATEGORIES[5]],
    features: [
      { id: 'f6', model_id: 'model-2', type: 'strength', content: '1M token context window', created_at: NOW },
      { id: 'f7', model_id: 'model-2', type: 'strength', content: 'Top-tier coding performance', created_at: NOW },
    ],
    pricing: { id: 'p2', model_id: 'model-2', input_price_per_1m_tokens: 2.00, output_price_per_1m_tokens: 8.00, pricing_type: 'paid', notes: 'Optimized for agents', created_at: NOW },
    metrics: { id: 'm2', model_id: 'model-2', reasoning: 4.7, coding: 5.0, speed: 4.2, latency: 4.0, creative_writing: 4.3, context_utilization: 5.0, created_at: NOW },
  },
  {
    id: 'model-3',
    name: 'Claude 3.5 Sonnet',
    provider: 'Anthropic',
    description: "Nuanced writing and excellent safety alignment. Great for professional content.",
    type: 'text',
    api_available: true,
    website_url: 'https://anthropic.com',
    rating: 4.7,
    context_window: 200000,
    overall_score: 4.5,
    last_updated: '2026-03-15',
    created_at: '2024-06-20',
    categories: [CATEGORIES[1], CATEGORIES[0], CATEGORIES[2]],
    features: [
      { id: 'f11', model_id: 'model-3', type: 'strength', content: 'Exceptional writing quality', created_at: NOW },
      { id: 'f12', model_id: 'model-3', type: 'strength', content: 'Strong safety features', created_at: NOW },
    ],
    pricing: { id: 'p3', model_id: 'model-3', input_price_per_1m_tokens: 3.00, output_price_per_1m_tokens: 15.00, pricing_type: 'paid', notes: 'Thinking available', created_at: NOW },
    metrics: { id: 'm3', model_id: 'model-3', reasoning: 4.5, coding: 4.6, speed: 3.8, latency: 3.5, creative_writing: 5.0, context_utilization: 4.5, created_at: NOW },
  },
  {
    id: 'model-6',
    name: 'Gemini 2.5 Pro',
    provider: 'Google',
    description: "State-of-the-art reasoning with advanced thinking mode and 1M context.",
    type: 'text',
    api_available: true,
    website_url: 'https://deepmind.google',
    rating: 4.9,
    context_window: 1000000,
    overall_score: 4.8,
    last_updated: '2026-03-15',
    created_at: '2025-03-25',
    categories: [CATEGORIES[2], CATEGORIES[0], CATEGORIES[8]],
    features: [
      { id: 'f26', model_id: 'model-6', type: 'strength', content: '#1 on multiple benchmarks', created_at: NOW },
      { id: 'f27', model_id: 'model-6', type: 'strength', content: 'Advanced thinking mode', created_at: NOW },
    ],
    pricing: { id: 'p6', model_id: 'model-6', input_price_per_1m_tokens: 1.25, output_price_per_1m_tokens: 10.00, pricing_type: 'paid', notes: 'Thinking tokens billed separately', created_at: NOW },
    metrics: { id: 'm6', model_id: 'model-6', reasoning: 5.0, coding: 4.9, speed: 3.5, latency: 3.2, creative_writing: 4.5, context_utilization: 5.0, created_at: NOW },
  },
  {
    id: 'model-12',
    name: 'Midjourney v6',
    provider: 'Midjourney',
    description: "Industry-leading artistic outputs. Preferred by designers for unique style.",
    type: 'image',
    api_available: false,
    website_url: 'https://midjourney.com',
    rating: 4.8,
    context_window: 0,
    overall_score: 4.5,
    last_updated: '2026-03-05',
    created_at: '2024-01-01',
    categories: [CATEGORIES[3]],
    features: [
      { id: 'f56', model_id: 'model-12', type: 'strength', content: 'Most aesthetic outputs', created_at: NOW },
      { id: 'f59', model_id: 'model-12', type: 'weakness', content: 'No public API', created_at: NOW },
    ],
    pricing: { id: 'p12', model_id: 'model-12', input_price_per_1m_tokens: 0, output_price_per_1m_tokens: 0, pricing_type: 'paid', notes: 'Monthly subscription', created_at: NOW },
    metrics: { id: 'm12', model_id: 'model-12', reasoning: 1.5, coding: 1.0, speed: 3.5, latency: 3.0, creative_writing: 5.0, context_utilization: 2.5, created_at: NOW },
  }
];
